name: Deploy 1

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Git clone in VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf /var/www/tmp
            mkdir /var/www/tmp
            cp /var/www/codante-io-front/.env.production /var/www/tmp/

            rm -rf /var/www/codante-io-front

            git clone --depth 1 git@github.com:codante-io/codante-io-front.git /var/www/codante-io-front

            cp /var/www/tmp/.env.production /var/www/codante-io-front/
            rm -rf /var/www/tmp

            cd /var/www/codante-io-front

            npm ci

      - name: Copy build folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./build"
          target: "/var/www/codante-io-front"

  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: production-files
  #         path: ./

  #     - name: Deploy to VPS
  #       uses: appleboy/ssh-action@scp-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.SSH_KEY }}
  #         source: "./"
  #         target: "/var/www/codante-io-front"
#  deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy with pm2
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_KEY }}
#           script: |
#             rm -rf /var/www/tmp
#             mkdir /var/www/tmp
#             cp /var/www/codante-io-front/.env.production /var/www/tmp/

#             rm -rf /var/www/codante-io-front

#             git clone --depth 1 git@github.com:codante-io/codante-io-front.git /var/www/codante-io-front

#             cp /var/www/tmp/.env.production /var/www/codante-io-front/
#             rm -rf /var/www/tmp

#             cd /var/www/codante-io-front

#             npm ci

#             # Increase memory to avoid vite build error

#             NODE_OPTIONS=--max_old_space_size=4096 npm run build

#             pm2 restart codante-io-front
